# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'password.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import random
from random import Random, randint

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 761, 71))
        font = QtGui.QFont()
        font.setPointSize(37)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.output = QtWidgets.QLabel(self.centralwidget)
        self.output.setGeometry(QtCore.QRect(10, 90, 761, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.output.setFont(font)
        self.output.setFrameShape(QtWidgets.QFrame.Box)
        self.output.setText("")
        self.output.setTextFormat(QtCore.Qt.PlainText)
        self.output.setObjectName("output")
        self.password = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.checked())
        self.password.setGeometry(QtCore.QRect(220, 340, 261, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.password.setFont(font)
        self.password.setObjectName("password")
        self.capital = QtWidgets.QCheckBox(self.centralwidget)
        self.capital.setGeometry(QtCore.QRect(200, 190, 281, 61))
        self.capital.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.capital.setObjectName("capital")
        self.minor = QtWidgets.QCheckBox(self.centralwidget)
        self.minor.setGeometry(QtCore.QRect(200, 250, 281, 61))
        self.minor.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.minor.setObjectName("minor")
        self.number = QtWidgets.QCheckBox(self.centralwidget)
        self.number.setGeometry(QtCore.QRect(400, 190, 281, 61))
        self.number.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.number.setObjectName("number")
        self.simbols = QtWidgets.QCheckBox(self.centralwidget)
        self.simbols.setGeometry(QtCore.QRect(400, 250, 281, 61))
        self.simbols.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.simbols.setObjectName("simbols")
        self.copy = QtWidgets.QPushButton(self.centralwidget)
        self.copy.setGeometry(QtCore.QRect(220, 430, 261, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.copy.setFont(font)
        self.copy.setObjectName("copy")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Password"))
        self.password.setText(_translate("MainWindow", "Nova Senha"))
        self.capital.setText(_translate("MainWindow", "Letras Maiusculas"))
        self.minor.setText(_translate("MainWindow", "Letras Minusculas"))
        self.number.setText(_translate("MainWindow", "Números"))
        self.simbols.setText(_translate("MainWindow", "Simbolos"))
        self.copy.setText(_translate("MainWindow", "Copiar"))
    


    def checked(self):
        if self.capital.isChecked()==True:
                maius="ABCDEFGHIJKLMNOPQRSTUVWXYZ"
                password=""
                for i in range(10):
                    i=random.choice(maius)
                    password=str(password)+i
                    self.output.setText(password)
              
        if self.minor.isChecked()==True:
                minus="abcdefghijklmnopqrstuvwxyz"
                password2=""
                for j in range(10):
                    j=random.choice(minus)
                    password2=str(password2)+j
                    self.output.setText(password2)
        if self.number.isChecked()==True:
                digits="0123456789"
                password3=""
                for a in range(10):
                    a=random.choice(digits)
                    password3=str(password3)+a
                    self.output.setText(password3)

        if self.simbols.isChecked()==True:
                simb="!@#$%^&*()"
                password4=""
                for z in range(10):
                    z=random.choice(simb)
                    password4=str(password4)+z
                    self.output.setText(password4)

        if self.capital.isChecked() and self.minor.isChecked()==True:
                senha=""
                foo=[i,j]
                for m in range(10):
                    m=random.choice(foo)
                    senha=str(senha)+m
                    self.output.setText(senha)

        if self.capital.isChecked() and self.number.isChecked()==True:
                senha2=""
                foo2=[i,a]
                for q in range(10):
                    q=random.choice(foo2)
                    senha2=str(senha2)+q
                    self.output.setText(senha2)

        if self.capital.isChecked() and self.simbols.isChecked()==True:
                senha5=""
                foo5=[i,z]
                for r in range(10):
                    r=random.choice(foo5)
                    senha5=str(senha5)+r
                    self.output.setText(senha5)        

        if self.capital.isChecked() and self.number.isChecked() and self.simbols.isChecked()==True:
                senha3=""
                foo3=[i,a,z]
                for w in range(10):
                    w=random.choice(foo3)
                    senha3=str(senha3)+w
                    self.output.setText(senha3)

        if self.capital.isChecked() and self.minor.isChecked() and self.number.isChecked() and self.simbols.isChecked()==True:
                senha4=""
                foo4=[i,j,a,z]
                
                for e in range(10):
                    e=random.choice(foo4)
                    senha4=str(senha4)+e
                    self.output.setText(senha4)
        
                    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())